### PR TITLE
Add many more options that can be read from the environment. Update u…

### LINKED ISSUE #372: Environmental variables in config
Please consider allowing environmental variables in the configuration such as for the redis_url; this makes the application more docker-compatible without having to do sed's against the configuration file prior to execution.

### PR DESCRIPTION
**Pull request by jhmartin**
Add many more options that can be read from the environment. Update usage to mention environmental variables.

Fixes #372

### CODE REVIEW

**Comment by josegonzalez** [comment]
Why weren't all the options updated?

Also, this needs some form of documentation :)

**Comment by jhmartin** [comment]
I left off the deprecated ones and the ones that seemed to be in the block listing command line arguments.

I added a line to the usage docs indicating most config file options are also available as environmental variables, in all caps.

**Comment by JamieCressey** [comment]
We should have some tests for the new functionality too. Perhaps just ensure the core settings, and the settings for transports which already have tests are covered?

**Comment by JamieCressey** [comment]
Ping @jhmartin , will you have chance to finish off this PR?

**Comment by jhmartin** [comment]
I should be able to submit the last of the env options, but my python knowledge and time isn't sufficient to add test cases for it.

**Comment by JamieCressey** [comment]
Closing due to inactivity. Feel free to reopen!

**Pull request closed without merging**
