### PR TITLE
kafka_codec require integer

### PR DESCRIPTION
**Pull request by cryptspirit**
solution of issue with enabling compression for kafka transport

### CODE REVIEW

**Comment by JamieCressey** [comment]
Thanks for the PR, please can you add tests for the new functionality you have added and docs so users know how to use it/what it does.

**Comment by JamieCressey** [comment]
Ping @cryptspirit do you have time to finish this off?

**Comment by cryptspirit** [comment]
Hello,

Sorry, but i worked with it when I have tested log forward agents for my work. The beaver has been discarded. I don't have any free time to finish this

**Comment by ersushantsood** [comment]
What was the reason you discarded beaver while using with kafka

**Comment by cryptspirit** [comment]
After losing connection to one broker beaver had a lot of errors and can't ahead processing logs. Beaver just stuck

**Pull request closed without merging**
