### PR TITLE
Added multiline_regex_begin option for multiline parsing

### PR DESCRIPTION
**Pull request by XooR**
I have log lines from log4j that sometimes have random line that is not space so I needed more strict method for multiline parsing like multiline_regex_begin.

### CODE REVIEW

**Comment by odyssey4me** [comment]
If I read this correctly, you're trying to implement an option where you can only match on a single line and have all other lines after it merge into the same event. This can already be done, for example here's a config for a mysql slow query log:

```
[/var/log/mysql/mysql-slow.log]
multiline_regex_after: (^#\sTime:\s)
multiline_regex_before: (.*)
```

**Comment by XooR** [comment]
Hello Jesse,
Your example won't work, here is simple code batch to test it out:
```
#!/usr/bin/env python

import pprint
import re
def multiline_merge(lines, current_event, re_after, re_before, re_begin):
    events = []
    for line in lines:
        if re_before and re_before.match(line):
            current_event.append(line)
        elif re_after and current_event and re_after.match(current_event[-1]):
            current_event.append(line)
        elif re_begin and not re_begin.match(line):
            current_event.append(line)
        else:
            if current_event:
                events.append('\n'.join(current_event))
            current_event.clear()
            current_event.append(line)

    return events

lines = [
"# Time: 150421 23:12:45",
"# User@Host: hello[hello2] @ localhost []",
"# Query_time: 1.123456  Lock_time: 0.000174 Rows_sent: 30  Rows_examined: 111",
"SET timestamp=142966000;",
"SELECT *",
"FROM some_table",
"WHERE something",
"# Time: 150421 23:16:48",
"# User@Host: hello[hello2] @ localhost []",
"# Query_time: 1.123456  Lock_time: 0.000174 Rows_sent: 30  Rows_examined: 111",
"SET timestamp=142966000;",
"SELECT *",
"FROM some_table",
"WHERE something"]

current_event = []
multiline_regex_before="(.*)"
multiline_regex_after="(^#\sTime:\s)"

res = multiline_merge(lines, current_event, re.compile(multiline_regex_after), re.compile(multiline_regex_before), None)
pprint.pprint( res )
```

It's possible to work, if you make a regex after that will match everything except timestamp on beginning. That kind of magic is possible but I don't won't to use it. Instead I opted for regex that would only tag some line as event beginning and code would guess that all other should be appended.

Correct me if I'm wrong :)

**Comment by odyssey4me** [comment]
@XooR Well, I can't necessarily explain the details of why it works - but I can say that it does appear to work in the test environment I had setup to do so. It seems to effectively do what you've set out to achieve, but it's quite possible that it may not work for some edge cases which I haven't tried yet.

**Comment by JamieCressey** [comment]
@XooR is this still needed? Can you provide a use case where `multiline_regex_after` and `multiline_regex_before` are insufficient?

**Pull request closed without merging**
