### PR TITLE
Added multiline_wait configuration key

### PR DESCRIPTION
**Pull request by KingdomOfJoy**
As was described at https://github.com/josegonzalez/beaver/issues/209 , I added multiline_wait configuration key with default value of 1 second (since this is what it currently is in the beaver).

I am not sure if it's completely correct but it works for me. Let me know if this change is sane.

Thank you!

### CODE REVIEW

**Comment by zhenghao1** [comment]
Has this been merged to master yet?  Can't seem to see the changes in master.

**Comment by josegonzalez** [comment]
Obviously not, given that the PR is still open.

**Comment by josegonzalez** [comment]
Needs to be added to tail.py as well.

**Comment by JamieCressey** [comment]
Closing due to inactivity. Feel free to reopen!

**Pull request closed without merging**
